config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  #this is a singleton w/o index
  #i.e. there is only one profile per user
  #no new either, as profile assumed and tacit
  resource :profile, :except => [:new, :create]
  resources :categories
  ##get '/categories/new/(:parent_id)', to: 'categories#new', as: :new_category

  resources :artifacts

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
  get 'dashboard' => 'dashboards#show', :as => 'user_root'
  root to: 'visitors#index'
  devise_for :users
  resources :users

end

app/models/artifact.rb
class Artifact < ActiveRecord::Base
  mount_uploader :myfile, ArtifactUploader
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized

  # GET /artifacts
  # GET /artifacts.json
  def index
    @artifacts = Artifact.all
    authorize Artifact
  end

  # GET /artifacts/1
  # GET /artifacts/1.json
  def show
    authorize @artifact
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    authorize @artifact
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts
  # POST /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)
    authorize @artifact
    respond_to do |format|
      if @artifact.save
        format.html { redirect_to @artifact, notice: 'Artifact was successfully created.' }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1
  # PATCH/PUT /artifacts/1.json
  def update
    authorize @artifact
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: 'Artifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1
  # DELETE /artifacts/1.json
  def destroy
    authorize @artifact
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: 'Artifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artifact_params
      params.require(:artifact).permit(:name, :file_type, :corpus, :catalog_number)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.slim
= simple_form_for(@artifact, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :file_type
    = f.input :corpus
    = f.input :catalog_number
    = f.input :myfile, label: "artifact", as: :attachment_preview
  .form-actions
    = f.button :submit

app/views/artifacts/edit.html.slim
h1 Editing artifact

== render 'form'

= link_to 'Show', @artifact
'|
= link_to 'Back', artifacts_path

app/views/artifacts/index.html.slim
h1 Listing artifacts

table
  thead
    tr
      th Name
      th File type
      th Corpus
      th Catalog number
      th
      th
      th

  tbody
    - @artifacts.each do |artifact|
      tr
        td = artifact.name
        td = artifact.file_type
        td = artifact.corpus
        td = artifact.catalog_number
        td = link_to 'Show', artifact
        td = link_to 'Edit', edit_artifact_path(artifact)
        td = link_to 'Destroy', artifact, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Artifact', new_artifact_path

app/views/artifacts/new.html.slim
h1 New artifact

== render 'form'

= link_to 'Back', artifacts_path

app/views/artifacts/show.html.slim
p#notice = notice

p
  strong Name:
  = @artifact.name
p
  strong File type:
  = @artifact.file_type
p
  strong Corpus:
  = @artifact.corpus
p
  strong Catalog number:
  = @artifact.catalog_number

= link_to 'Edit', edit_artifact_path(@artifact)
'|
= link_to 'Back', artifacts_path